default:
  Addr: 127.0.0.1:6379,127.0.0.1:6379,127.0.0.1:6379
  Password: 123456
  MaxActive: 64 
  MaxIdle: 16  
  IdleTimeout: 240s    
  ConnectTimeout: 10s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  TestInterval: 60s
