//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//BOTISLAND auto
type BOTISLAND struct {
	ID        int    //#
	Name      string //机器人名字
	HeadIcon  string //机器人头像
	LEVEL     int    //机器人等级
	LikeCount int    //机器人初始点赞数
	MAPNAME   string //机器人地图文件名
	BuyData   []int  //付费岛1，付费岛2的购买情况，0没买 1 买了
	UnlockID  int    //解云的数量
}

//IBOTISLAND auto
type IBOTISLAND interface {
	GetID() int
	GetName() string
	GetHeadIcon() string
	GetLEVEL() int
	GetLikeCount() int
	GetMAPNAME() string
	GetBuyDataLen() int
	GetBuyDataByIndex(index int) int
	GetUnlockID() int
}

//GetID auto
func (b *BOTISLAND) GetID() int {
	return b.ID
}

//GetName auto
func (b *BOTISLAND) GetName() string {
	return b.Name
}

//GetHeadIcon auto
func (b *BOTISLAND) GetHeadIcon() string {
	return b.HeadIcon
}

//GetLEVEL auto
func (b *BOTISLAND) GetLEVEL() int {
	return b.LEVEL
}

//GetLikeCount auto
func (b *BOTISLAND) GetLikeCount() int {
	return b.LikeCount
}

//GetMAPNAME auto
func (b *BOTISLAND) GetMAPNAME() string {
	return b.MAPNAME
}

//GetBuyDataLen auto
func (b *BOTISLAND) GetBuyDataLen() int {
	return len(b.BuyData)
}

//GetBuyDataByIndex auto
func (b *BOTISLAND) GetBuyDataByIndex(index int) int {
	return b.BuyData[index]
}

//GetUnlockID auto
func (b *BOTISLAND) GetUnlockID() int {
	return b.UnlockID
}
