//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//BOTFRIENDCONFIG auto
type BOTFRIENDCONFIG struct {
	ID         int   //#
	LEVELRANGE []int //玩家关卡区间，前闭后开
	BOTID      []int //机器人推荐，添加好友池
}

//IBOTFRIENDCONFIG auto
type IBOTFRIENDCONFIG interface {
	GetID() int
	GetLEVELRANGELen() int
	GetLEVELRANGEByIndex(index int) int
	GetBOTIDLen() int
	GetBOTIDByIndex(index int) int
}

//GetID auto
func (b *BOTFRIENDCONFIG) GetID() int {
	return b.ID
}

//GetLEVELRANGELen auto
func (b *BOTFRIENDCONFIG) GetLEVELRANGELen() int {
	return len(b.LEVELRANGE)
}

//GetLEVELRANGEByIndex auto
func (b *BOTFRIENDCONFIG) GetLEVELRANGEByIndex(index int) int {
	return b.LEVELRANGE[index]
}

//GetBOTIDLen auto
func (b *BOTFRIENDCONFIG) GetBOTIDLen() int {
	return len(b.BOTID)
}

//GetBOTIDByIndex auto
func (b *BOTFRIENDCONFIG) GetBOTIDByIndex(index int) int {
	return b.BOTID[index]
}
