//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//FRIENDDELAY auto
type FRIENDDELAY struct {
	ID          int   //#
	ACCEPTDELAY []int //接受好友延迟，范围单位为秒
}

//IFRIENDDELAY auto
type IFRIENDDELAY interface {
	GetID() int
	GetACCEPTDELAYLen() int
	GetACCEPTDELAYByIndex(index int) int
}

//GetID auto
func (f *FRIENDDELAY) GetID() int {
	return f.ID
}

//GetACCEPTDELAYLen auto
func (f *FRIENDDELAY) GetACCEPTDELAYLen() int {
	return len(f.ACCEPTDELAY)
}

//GetACCEPTDELAYByIndex auto
func (f *FRIENDDELAY) GetACCEPTDELAYByIndex(index int) int {
	return f.ACCEPTDELAY[index]
}
