//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//Maxleveltournament auto
type Maxleveltournament struct {
	ID          int    //活动id
	TypeID      int    //活动类型 10001=满级玩法
	StartTime   string //活动开始时间 配置方式为{年，月，日，小时，分，秒} 其中小时是24小时制
	EndTime     string //活动截止时间 配置方式为{年，月，日，小时，分，秒} 其中小时是24小时制
	RegisterEnd int    //小组创建截止时间 单位/秒 例： 值为10时表示在活动截止时间前10秒禁止创建新的分组
	GroupSize   int    //活动每个分组内人数 单位/人 例： 值为0时表示分组没有人数限制 值为20时表示每个分组最多20人
	GroupDelay  int    //分组未满人过期关闭时间 单位/秒 例： 值为0时表示没有过期关闭时间 值为10时表示小组创建10秒后及时未满也关闭该小组
}

//IMaxleveltournament auto
type IMaxleveltournament interface {
	GetID() int
	GetTypeID() int
	GetStartTime() string
	GetEndTime() string
	GetRegisterEnd() int
	GetGroupSize() int
	GetGroupDelay() int
}

//GetID auto
func (m *Maxleveltournament) GetID() int {
	return m.ID
}

//GetTypeID auto
func (m *Maxleveltournament) GetTypeID() int {
	return m.TypeID
}

//GetStartTime auto
func (m *Maxleveltournament) GetStartTime() string {
	return m.StartTime
}

//GetEndTime auto
func (m *Maxleveltournament) GetEndTime() string {
	return m.EndTime
}

//GetRegisterEnd auto
func (m *Maxleveltournament) GetRegisterEnd() int {
	return m.RegisterEnd
}

//GetGroupSize auto
func (m *Maxleveltournament) GetGroupSize() int {
	return m.GroupSize
}

//GetGroupDelay auto
func (m *Maxleveltournament) GetGroupDelay() int {
	return m.GroupDelay
}
