//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//MEDALRUSHUSERGROUPCONFIG auto
type MEDALRUSHUSERGROUPCONFIG struct {
	ID             int    //#
	LEVELRANGE     []int  //关卡区间 前闭后开 -1表示满级玩家/精英赛玩家；0表示主线最大关卡
	EVENTCOUNTDOWN []int  //距离活动结束的时间范围，前闭后开，单位为秒
	USERTYPE       int    //用户种类 1：付费用户 ；0：免费用户
	AVGRANKING     string //最近1次排名
	GROUPTYPE      string //排名对应分组参数表id
}

//IMEDALRUSHUSERGROUPCONFIG auto
type IMEDALRUSHUSERGROUPCONFIG interface {
	GetID() int
	GetLEVELRANGELen() int
	GetLEVELRANGEByIndex(index int) int
	GetEVENTCOUNTDOWNLen() int
	GetEVENTCOUNTDOWNByIndex(index int) int
	GetUSERTYPE() int
	GetAVGRANKING() string
	GetGROUPTYPE() string
}

//GetID auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetID() int {
	return m.ID
}

//GetLEVELRANGELen auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetLEVELRANGELen() int {
	return len(m.LEVELRANGE)
}

//GetLEVELRANGEByIndex auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetLEVELRANGEByIndex(index int) int {
	return m.LEVELRANGE[index]
}

//GetEVENTCOUNTDOWNLen auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetEVENTCOUNTDOWNLen() int {
	return len(m.EVENTCOUNTDOWN)
}

//GetEVENTCOUNTDOWNByIndex auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetEVENTCOUNTDOWNByIndex(index int) int {
	return m.EVENTCOUNTDOWN[index]
}

//GetUSERTYPE auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetUSERTYPE() int {
	return m.USERTYPE
}

//GetAVGRANKING auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetAVGRANKING() string {
	return m.AVGRANKING
}

//GetGROUPTYPE auto
func (m *MEDALRUSHUSERGROUPCONFIG) GetGROUPTYPE() string {
	return m.GROUPTYPE
}
