//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//MEDALRUSHGROUPCONFIG auto
type MEDALRUSHGROUPCONFIG struct {
	ID                 int    //#
	GROUPSIZE          int    //分组最大人数
	INITBOTGROUPID     string //初始机器人分组
	INITBOTCOUNT       string //初始机器人数量范围
	FILLRANGE          string //建组后时间区间，左闭右开，单位秒
	FILLCD             string //建组后时间区间对应机器人填充间隔，单位为秒
	FILLBOTCOUNT       string //填充机器人数量范围
	FILLBOTGROUPID     string //填充机器人分组
	FILLBOTWEIGHT      string //填充机器人分组对应权重
	FULLFILLTIME       int    //机器人填充最大时间，单位为秒
	MINPLAYERNUM       int    //最小真人个数
	MAXPLAYERNUM       int    //最大真人个数
	FULLFILLBOTGROUPID []int  //一次性填充机器人分组
	FULLFILLBOTWEIGHT  []int  //一次性填充机器人分组对应权重
}

//IMEDALRUSHGROUPCONFIG auto
type IMEDALRUSHGROUPCONFIG interface {
	GetID() int
	GetGROUPSIZE() int
	GetINITBOTGROUPID() string
	GetINITBOTCOUNT() string
	GetFILLRANGE() string
	GetFILLCD() string
	GetFILLBOTCOUNT() string
	GetFILLBOTGROUPID() string
	GetFILLBOTWEIGHT() string
	GetFULLFILLTIME() int
	GetMINPLAYERNUM() int
	GetMAXPLAYERNUM() int
	GetFULLFILLBOTGROUPIDLen() int
	GetFULLFILLBOTGROUPIDByIndex(index int) int
	GetFULLFILLBOTWEIGHTLen() int
	GetFULLFILLBOTWEIGHTByIndex(index int) int
}

//GetID auto
func (m *MEDALRUSHGROUPCONFIG) GetID() int {
	return m.ID
}

//GetGROUPSIZE auto
func (m *MEDALRUSHGROUPCONFIG) GetGROUPSIZE() int {
	return m.GROUPSIZE
}

//GetINITBOTGROUPID auto
func (m *MEDALRUSHGROUPCONFIG) GetINITBOTGROUPID() string {
	return m.INITBOTGROUPID
}

//GetINITBOTCOUNT auto
func (m *MEDALRUSHGROUPCONFIG) GetINITBOTCOUNT() string {
	return m.INITBOTCOUNT
}

//GetFILLRANGE auto
func (m *MEDALRUSHGROUPCONFIG) GetFILLRANGE() string {
	return m.FILLRANGE
}

//GetFILLCD auto
func (m *MEDALRUSHGROUPCONFIG) GetFILLCD() string {
	return m.FILLCD
}

//GetFILLBOTCOUNT auto
func (m *MEDALRUSHGROUPCONFIG) GetFILLBOTCOUNT() string {
	return m.FILLBOTCOUNT
}

//GetFILLBOTGROUPID auto
func (m *MEDALRUSHGROUPCONFIG) GetFILLBOTGROUPID() string {
	return m.FILLBOTGROUPID
}

//GetFILLBOTWEIGHT auto
func (m *MEDALRUSHGROUPCONFIG) GetFILLBOTWEIGHT() string {
	return m.FILLBOTWEIGHT
}

//GetFULLFILLTIME auto
func (m *MEDALRUSHGROUPCONFIG) GetFULLFILLTIME() int {
	return m.FULLFILLTIME
}

//GetMINPLAYERNUM auto
func (m *MEDALRUSHGROUPCONFIG) GetMINPLAYERNUM() int {
	return m.MINPLAYERNUM
}

//GetMAXPLAYERNUM auto
func (m *MEDALRUSHGROUPCONFIG) GetMAXPLAYERNUM() int {
	return m.MAXPLAYERNUM
}

//GetFULLFILLBOTGROUPIDLen auto
func (m *MEDALRUSHGROUPCONFIG) GetFULLFILLBOTGROUPIDLen() int {
	return len(m.FULLFILLBOTGROUPID)
}

//GetFULLFILLBOTGROUPIDByIndex auto
func (m *MEDALRUSHGROUPCONFIG) GetFULLFILLBOTGROUPIDByIndex(index int) int {
	return m.FULLFILLBOTGROUPID[index]
}

//GetFULLFILLBOTWEIGHTLen auto
func (m *MEDALRUSHGROUPCONFIG) GetFULLFILLBOTWEIGHTLen() int {
	return len(m.FULLFILLBOTWEIGHT)
}

//GetFULLFILLBOTWEIGHTByIndex auto
func (m *MEDALRUSHGROUPCONFIG) GetFULLFILLBOTWEIGHTByIndex(index int) int {
	return m.FULLFILLBOTWEIGHT[index]
}
