//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//RobotName auto
type RobotName struct {
	ID   int    //#
	Name string //机器人名称
}

//IRobotName auto
type IRobotName interface {
	GetID() int
	GetName() string
}

//GetID auto
func (r *RobotName) GetID() int {
	return r.ID
}

//GetName auto
func (r *RobotName) GetName() string {
	return r.Name
}
