//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//System auto
type System struct {
	ID                      int //ID
	MaxLevel                int //满级关卡号
	GuildLevelLimit         int //公会限制等级
	GuildMaxNum             int //公会最大人数
	GuildActivityLevelLimit int //公会活动参与限制
	HelpInterval            int //公会帮助间隔
	MaxUnAckHelpCnt         int //最大待消费的请求体力
	MaxUnfinishedHelpCnt    int //单次拉取未完成的最大帮助个数
	GuildRankCount          int //公会排行榜数量
	UserRankCount           int //玩家排行榜数量
}

//ISystem auto
type ISystem interface {
	GetID() int
	GetMaxLevel() int
	GetGuildLevelLimit() int
	GetGuildMaxNum() int
	GetGuildActivityLevelLimit() int
	GetHelpInterval() int
	GetMaxUnAckHelpCnt() int
	GetMaxUnfinishedHelpCnt() int
	GetGuildRankCount() int
	GetUserRankCount() int
}

//GetID auto
func (s *System) GetID() int {
	return s.ID
}

//GetMaxLevel auto
func (s *System) GetMaxLevel() int {
	return s.MaxLevel
}

//GetGuildLevelLimit auto
func (s *System) GetGuildLevelLimit() int {
	return s.GuildLevelLimit
}

//GetGuildMaxNum auto
func (s *System) GetGuildMaxNum() int {
	return s.GuildMaxNum
}

//GetGuildActivityLevelLimit auto
func (s *System) GetGuildActivityLevelLimit() int {
	return s.GuildActivityLevelLimit
}

//GetHelpInterval auto
func (s *System) GetHelpInterval() int {
	return s.HelpInterval
}

//GetMaxUnAckHelpCnt auto
func (s *System) GetMaxUnAckHelpCnt() int {
	return s.MaxUnAckHelpCnt
}

//GetMaxUnfinishedHelpCnt auto
func (s *System) GetMaxUnfinishedHelpCnt() int {
	return s.MaxUnfinishedHelpCnt
}

//GetGuildRankCount auto
func (s *System) GetGuildRankCount() int {
	return s.GuildRankCount
}

//GetUserRankCount auto
func (s *System) GetUserRankCount() int {
	return s.UserRankCount
}
