//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//Teamchestgroup auto
type Teamchestgroup struct {
	GroupID    int //#
	LevelStart int //区间开始等级
	LevelEnd   int //区间结束等级
	Goal       int //阶段目标1
	Goal2      int //阶段目标2
	Goal3      int //阶段目标3
}

//ITeamchestgroup auto
type ITeamchestgroup interface {
	GetGroupID() int
	GetLevelStart() int
	GetLevelEnd() int
	GetGoal() int
	GetGoal2() int
	GetGoal3() int
}

//GetGroupID auto
func (t *Teamchestgroup) GetGroupID() int {
	return t.GroupID
}

//GetLevelStart auto
func (t *Teamchestgroup) GetLevelStart() int {
	return t.LevelStart
}

//GetLevelEnd auto
func (t *Teamchestgroup) GetLevelEnd() int {
	return t.LevelEnd
}

//GetGoal auto
func (t *Teamchestgroup) GetGoal() int {
	return t.Goal
}

//GetGoal2 auto
func (t *Teamchestgroup) GetGoal2() int {
	return t.Goal2
}

//GetGoal3 auto
func (t *Teamchestgroup) GetGoal3() int {
	return t.Goal3
}
