//Package csvauto GENERATED BY CSV AUTO; DO NOT EDIT
package csvauto

//Teamchesttime auto
type Teamchesttime struct {
	ID         int   //#
	Type       int   //类型
	Startpoint int   //天
	StartTime  []int //活动开启时间
	Endpoint   int
	EndTime    []int //活动结束时间
	ShowTime   int   //公示结束时间 单位/秒
	EventType  int   //活动类型
}

//ITeamchesttime auto
type ITeamchesttime interface {
	GetID() int
	GetType() int
	GetStartpoint() int
	GetStartTimeLen() int
	GetStartTimeByIndex(index int) int
	GetEndpoint() int
	GetEndTimeLen() int
	GetEndTimeByIndex(index int) int
	GetShowTime() int
	GetEventType() int
}

//GetID auto
func (t *Teamchesttime) GetID() int {
	return t.ID
}

//GetType auto
func (t *Teamchesttime) GetType() int {
	return t.Type
}

//GetStartpoint auto
func (t *Teamchesttime) GetStartpoint() int {
	return t.Startpoint
}

//GetStartTimeLen auto
func (t *Teamchesttime) GetStartTimeLen() int {
	return len(t.StartTime)
}

//GetStartTimeByIndex auto
func (t *Teamchesttime) GetStartTimeByIndex(index int) int {
	return t.StartTime[index]
}

//GetEndpoint auto
func (t *Teamchesttime) GetEndpoint() int {
	return t.Endpoint
}

//GetEndTimeLen auto
func (t *Teamchesttime) GetEndTimeLen() int {
	return len(t.EndTime)
}

//GetEndTimeByIndex auto
func (t *Teamchesttime) GetEndTimeByIndex(index int) int {
	return t.EndTime[index]
}

//GetShowTime auto
func (t *Teamchesttime) GetShowTime() int {
	return t.ShowTime
}

//GetEventType auto
func (t *Teamchesttime) GetEventType() int {
	return t.EventType
}
